// Offline generator for the preflop Equity table.
//
// Run with: node scripts/generate-preflop-table.ts
//
// Every number it writes is computed here, by this repository's own evaluator —
// the one verified against all 133,784,560 seven-card hands. Nothing is
// transcribed from a published table: the well-known ones come out of
// copyrighted books, and several repositories carrying that data ship no licence
// at all. Since we already have a trustworthy evaluator, generating our own is a
// one-off script rather than a legal question.
//
// It is deterministic: the seed for each cell is derived from its position, so
// re-running reproduces the file byte for byte.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { monteCarloEquity } from '../src/poker-math/equity-core.ts';
import { allCanonicalLabels, representativeCards } from '../src/poker-math/starting-hands.ts';
import { seededRng } from '../src/poker-math/rng.ts';

const ITERATIONS = 200_000;
const BASE_SEED = 20_260_824;
const MAX_OPPONENTS = 5;
const OUTPUT = fileURLToPath(
  new URL('../src/poker-math/preflop-equity-table.json', import.meta.url),
);

const labels = allCanonicalLabels();
const table: Record<string, number[]> = {};

const started = Date.now();
let cell = 0;

for (const [index, label] of labels.entries()) {
  const hole = representativeCards(label);
  const row: number[] = [];

  for (let opponents = 1; opponents <= MAX_OPPONENTS; opponents++) {
    const rng = seededRng(BASE_SEED + index * 1000 + opponents);
    const { equity } = monteCarloEquity({
      hole,
      board: [],
      opponentCount: opponents,
      rng,
      iterations: ITERATIONS,
    });
    // Six decimals: far beyond the sampling error, and it keeps the file stable.
    row.push(Number(equity.toFixed(6)));
    cell++;
  }

  table[label] = row;
  const done = index + 1;
  process.stderr.write(
    `\r${String(done).padStart(3)}/${labels.length}  ${label.padEnd(4)}  ` +
      `${((Date.now() - started) / 1000).toFixed(0)}s`,
  );
}

// 1σ for a proportion, at its worst (p = 0.5).
const sigma = Math.sqrt(0.25 / ITERATIONS);

const payload = {
  iterations: ITERATIONS,
  seed: BASE_SEED,
  maxOpponents: MAX_OPPONENTS,
  note:
    `Generated by scripts/generate-preflop-table.ts using this repository's own evaluator. ` +
    `${ITERATIONS} seeded Monte Carlo iterations per cell against uniformly random opponent ` +
    `hands, so the worst-case 1-sigma error is about ${(sigma * 100).toFixed(3)}%. ` +
    `Deterministic: re-running reproduces this file exactly. No published or copyrighted ` +
    `table was consulted.`,
  table,
};

writeFileSync(OUTPUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');

process.stderr.write(
  `\ndone: ${cell} cells in ${((Date.now() - started) / 1000).toFixed(1)}s -> ${OUTPUT}\n`,
);
