// Offline generator for the preflop hand-category table.
//
// Run with: node scripts/generate-preflop-hand-odds.ts
//
// Unlike the Equity table, this one is genuinely exhaustive rather than sampled.
// "What will I end up with?" does not involve the opponents at all, so the only
// thing to enumerate is the board: C(50,5) = 2,118,760 of them per starting hand,
// and 169 canonical starting hands. 358 million evaluations, about a minute.
//
// Counts are stored rather than probabilities, so the file is exactly right and
// `sum(counts) === 2118760` is a property the tests can check.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DECK_SIZE } from '../src/poker-math/cards.ts';
import { categoryOf, evaluateHand } from '../src/poker-math/evaluate-hand.ts';
import { allCanonicalLabels, representativeCards } from '../src/poker-math/starting-hands.ts';

const BOARDS_PER_HAND = 2_118_760; // C(50,5)
const OUTPUT = fileURLToPath(
  new URL('../src/poker-math/preflop-hand-odds-table.json', import.meta.url),
);

const labels = allCanonicalLabels();
const table: Record<string, number[]> = {};
const hand = new Int32Array(7);
const started = Date.now();

for (const [index, label] of labels.entries()) {
  const hole = representativeCards(label);
  hand[0] = hole[0];
  hand[1] = hole[1];

  const live = new Int32Array(DECK_SIZE - 2);
  let size = 0;
  for (let card = 0; card < DECK_SIZE; card++) {
    if (card !== hole[0] && card !== hole[1]) live[size++] = card;
  }

  const counts = new Float64Array(9);
  let boards = 0;

  for (let a = 0; a < size - 4; a++) {
    hand[2] = live[a]!;
    for (let b = a + 1; b < size - 3; b++) {
      hand[3] = live[b]!;
      for (let c = b + 1; c < size - 2; c++) {
        hand[4] = live[c]!;
        for (let d = c + 1; d < size - 1; d++) {
          hand[5] = live[d]!;
          for (let e = d + 1; e < size; e++) {
            hand[6] = live[e]!;
            counts[categoryOf(evaluateHand(hand))]!++;
            boards++;
          }
        }
      }
    }
  }

  if (boards !== BOARDS_PER_HAND) throw new Error(`${label}: enumerated ${boards} boards`);
  table[label] = Array.from(counts);

  process.stderr.write(
    `\r${String(index + 1).padStart(3)}/${labels.length}  ${label.padEnd(4)}  ` +
      `${((Date.now() - started) / 1000).toFixed(0)}s`,
  );
}

const payload = {
  method: 'exhaustive-enumeration',
  boardsPerHand: BOARDS_PER_HAND,
  categories: ['高牌', '一对', '两对', '三条', '顺子', '同花', '葫芦', '四条', '同花顺'],
  note:
    `Generated by scripts/generate-preflop-hand-odds.ts using this repository's own ` +
    `evaluator. Every one of the C(50,5) = ${BOARDS_PER_HAND} boards is enumerated for each ` +
    `of the 169 canonical starting hands, so these counts are exact, not sampled. Values are ` +
    `counts indexed by hand category 0..8 (high card first, straight flush last). No published ` +
    `or copyrighted table was consulted.`,
  table,
};

writeFileSync(OUTPUT, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');
process.stderr.write(
  `\ndone: ${labels.length} hands in ${((Date.now() - started) / 1000).toFixed(1)}s -> ${OUTPUT}\n`,
);
