// Offline generator for the preflop Equity table.
//
// Run with: node scripts/generate-preflop-table.ts
//
// Every number it writes is computed here, by this repository's own evaluator —
// the one verified against all 133,784,560 seven-card hands. Nothing is
// transcribed from a published table: the well-known ones come out of
// copyrighted books, and several repositories carrying that data ship no licence
// at all. Since we already have a trustworthy evaluator, generating our own is a
// one-off script rather than a legal question.
//
// It is deterministic: the seed for each cell is derived from its position, so
// re-running reproduces the file byte for byte.
//
// Why sampled rather than enumerated. Exhausting one preflop cell means every
// opponent holding times every board — C(50,2) x C(48,5) = 2.1e9 showdowns for a
// single opponent, and the table has 845 cells. At the evaluator's measured ~6M
// hands per second that is months of CPU. 200,000 seeded iterations per cell puts
// the worst-case 1-sigma error at 0.112% and finishes in a couple of minutes. The
// table is therefore *reproducible* and *ours*, but it is not exact to the last
// decimal, and the metadata written below says so rather than implying otherwise.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { monteCarloEquity } from '../src/poker-math/equity-core.ts';
import { allCanonicalLabels, representativeCards } from '../src/poker-math/starting-hands.ts';
import { seededRng } from '../src/poker-math/rng.ts';

const ITERATIONS = 200_000;
const BASE_SEED = 20_260_824;
const MAX_OPPONENTS = 5;
const OUTPUT = fileURLToPath(
  new URL('../src/poker-math/preflop-equity-table.json', import.meta.url),
);

const labels = allCanonicalLabels();
const table: Record<string, string[]> = {};

const started = Date.now();
let cells = 0;

for (const [index, label] of labels.entries()) {
  const hole = representativeCards(label);
  const row: string[] = [];

  for (let opponents = 1; opponents <= MAX_OPPONENTS; opponents++) {
    const rng = seededRng(BASE_SEED + index * 1000 + opponents);
    const { equity, win, tie } = monteCarloEquity({
      hole,
      board: [],
      opponentCount: opponents,
      rng,
      iterations: ITERATIONS,
    });
    // `win` and `tie` are counts over ITERATIONS, so six decimals holds them
    // exactly. `equity` is win + tie/2, a multiple of 1/(2 * ITERATIONS), so six
    // decimals rounds it by at most 5e-7 — far under the sampling error, and it
    // keeps the file stable across runs.
    row.push(`[${equity.toFixed(6)}, ${win.toFixed(6)}, ${tie.toFixed(6)}]`);
    cells++;
  }

  table[label] = row;
  const done = index + 1;
  process.stderr.write(
    `\r${String(done).padStart(3)}/${labels.length}  ${label.padEnd(4)}  ` +
      `${((Date.now() - started) / 1000).toFixed(0)}s`,
  );
}

// 1σ for a proportion, at its worst (p = 0.5).
const sigma = Math.sqrt(0.25 / ITERATIONS);

const meta: Record<string, string | number> = {
  generatedBy: 'scripts/generate-preflop-table.ts',
  method: 'seeded Monte Carlo against uniformly random opponent hands',
  iterations: ITERATIONS,
  seed: BASE_SEED,
  maxOpponents: MAX_OPPONENTS,
  cellFormat: '[equity, win, tie] — equity is win + tie / 2',
  note:
    `Generated by scripts/generate-preflop-table.ts using this repository's own evaluator. ` +
    `${ITERATIONS} seeded Monte Carlo iterations per cell against uniformly random opponent ` +
    `hands, so the worst-case 1-sigma error is about ${(sigma * 100).toFixed(3)}%. These are ` +
    `sampled values, not enumerated ones: exhausting one cell is 2.1e9 showdowns. ` +
    `Deterministic: re-running reproduces this file exactly. No published or copyrighted ` +
    `table was consulted.`,
};

// Written by hand rather than through `JSON.stringify(value, null, 2)`, which
// would break each three-number cell across three lines. One cell per line keeps
// the file readable and its diffs meaningful.
const head = Object.entries(meta)
  .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
  .join('\n');
const body = labels
  .map((label) => {
    const cells = table[label]!.map((cell) => `      ${cell}`).join(',\n');
    return `    ${JSON.stringify(label)}: [\n${cells}\n    ]`;
  })
  .join(',\n');
const json = `{\n${head}\n  "table": {\n${body}\n  }\n}\n`;

JSON.parse(json); // Cheap guard against a formatting slip shipping broken data.
writeFileSync(OUTPUT, json, 'utf8');

process.stderr.write(
  `\ndone: ${cells} cells in ${((Date.now() - started) / 1000).toFixed(1)}s -> ${OUTPUT}\n`,
);
